name: Run Scraper to Update Component Prices

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    # Set the default working directory for all steps in this job
    defaults:
      run:
        working-directory: ./pc-banai

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        # This command now runs inside the 'pc-banai' directory
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper/requirements.txt

      - name: Run the scraper
        env:
          # The secret is repository-wide, so it's available here
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        # We specify a different working directory just for this step
        run: python scraper.py
        working-directory: ./pc-banai/scraper
