name: Run Scraper to Update Component Prices

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./pc-banai

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper/requirements.txt

      - name: Run the scraper
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        run: python scraper.py
        working-directory: ./pc-banai/scraper
