name: Scrape Data

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r pc-banai/scraper/requirements.txt

    - name: Run scraper
      env:
        # This passes your new pooled URL secret to the scraper script
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: python pc-banai/scraper/scraper.py
